label define Var 1 `"eadmsel"', modify
label define Var 2 `"emissel"', modify
label define Var 3 `"earbsel"', modify
label define Var 4 `"eseladm"', modify
label define Var 5 `"emisadm"', modify
label define Var 6 `"earbadm"', modify
label define Var 7 `"eselmis"', modify
label define Var 8 `"eadmmis"', modify
label define Var 9 `"earbmis"', modify
label define Var 10 `"eselarb"', modify
label define Var 11 `"eadmarb"', modify
label define Var 12 `"emisarb"', modify
label define Var 13 `"ealos"', modify
label define Var 14 `"eest"', modify
label define Var 15 `"easchul"', modify
label define Var 16 `"ehschul"', modify
label define Var 17 `"ebschul"', modify
label define Var 18 `"ebstart"', modify
label define Var 19 `"ehoch1"', modify
label define Var 20 `"ekind1"', modify
label define Var 21 `"ekind2"', modify
label define Var 22 `"eparspd"', modify
label define Var 23 `"eparkons"', modify
label define Var 24 `"eparb90"', modify
